import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import OpenAI from "openai";
import webpush from "web-push";
import { createServer } from "http";
import { Server } from "socket.io";
import { v4 as uuidv4 } from "uuid";
import { q } from "./db.js";

dotenv.config();
const app=express();
const http=createServer(app);
const allowed=(process.env.FRONTEND_ORIGIN||'*').split(',').map(x=>x.trim());
const corsOpts={origin:(origin,cb)=>{if(!origin||allowed.includes('*')||allowed.includes(origin))return cb(null,true);cb(new Error('CORS blocked'));},credentials:true};
app.use(cors(corsOpts)); app.use(express.json({limit:'1mb'})); app.use(express.static('public'));
const io=new Server(http,{cors:corsOpts});
const SECRET=process.env.JWT_SECRET||'change-me';
const ai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const pushReady=!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT);
if(pushReady) webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);

const tok=u=>jwt.sign({id:u.id,role:u.role,name:u.full_name},SECRET,{expiresIn:'7d'});
const auth=(roles=[])=>(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);if(roles.length&&!roles.includes(req.user.role))return res.status(403).json({error:'Not allowed'});next()}catch{return res.status(401).json({error:'Login required'})}};
const needAI=(req,res,next)=>ai?next():res.status(503).json({error:'Real AI is not configured. Add OPENAI_API_KEY in backend .env and restart.'});
io.on('connection',s=>s.on('identify',d=>d?.userId&&s.join('user:'+d.userId)));
async function act(kid,type,subject,title,meta={}){await q('INSERT INTO activities(kid_id,activity_type,subject,title,metadata) VALUES($1,$2,$3,$4,$5::jsonb)',[kid,type,subject||null,title||null,JSON.stringify(meta)])}
async function sendPush(uid,title,body){if(!pushReady)return;const rows=(await q('SELECT id,subscription FROM push_subscriptions WHERE user_id=$1',[uid])).rows;for(const r of rows){try{await webpush.sendNotification(r.subscription,JSON.stringify({title,body,url:'/'}));}catch(e){if([404,410].includes(e.statusCode))await q('DELETE FROM push_subscriptions WHERE id=$1',[r.id]);}}}
async function notify(kid,type,msg){const x=(await q('SELECT parent_id,teacher_id FROM kid_profiles WHERE user_id=$1',[kid])).rows[0]||{};for(const uid of [x.parent_id,x.teacher_id].filter(Boolean)){await q('INSERT INTO notifications(user_id,kid_id,type,message) VALUES($1,$2,$3,$4)',[uid,kid,type,msg]);io.to('user:'+uid).emit('notification',{message:msg,type,kidId:kid});await sendPush(uid,'LearnMate AI',msg)}}
async function kidContext(kid){const p=(await q('SELECT u.full_name,u.student_code,kp.* FROM users u JOIN kid_profiles kp ON kp.user_id=u.id WHERE u.id=$1',[kid])).rows[0];const today=(await q('SELECT subject,topic,instructions FROM teacher_assignments WHERE teacher_id=$1 AND board=$2 AND standard=$3 AND assignment_date=CURRENT_DATE ORDER BY id DESC',[p.teacher_id,p.board,p.standard])).rows;const mastery=(await q('SELECT subject,topic,score,attempts,next_revision_at FROM mastery WHERE kid_id=$1 ORDER BY score ASC NULLS LAST LIMIT 20',[kid])).rows;return {p,today,mastery}}
function cleanJSON(s){s=(s||'').trim().replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim();const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)s=s.slice(a,b+1);return JSON.parse(s)}
async function aiJSON(instructions,input,max=1800){const r=await ai.responses.create({model:MODEL,instructions,input,max_output_tokens:max});return cleanJSON(r.output_text)}
async function aiText(instructions,input,max=900){const r=await ai.responses.create({model:MODEL,instructions,input,max_output_tokens:max});return r.output_text||''}

app.post('/api/auth/login',async(req,res)=>{try{let {role,email,password,studentCode,pin}=req.body,u;if(role==='kid'){u=(await q("SELECT * FROM users WHERE role='kid' AND student_code=$1",[(studentCode||'').toUpperCase()])).rows[0];if(!u||!await bcrypt.compare(pin||'',u.pin_hash||''))return res.status(401).json({error:'Invalid Student ID or PIN'});const s=(await q('INSERT INTO learning_sessions(kid_id) VALUES($1) RETURNING id',[u.id])).rows[0];await act(u.id,'login',null,'Student logged in',{sessionId:s.id});await notify(u.id,'kid_login',u.full_name+' logged in.');const profile=(await q('SELECT * FROM kid_profiles WHERE user_id=$1',[u.id])).rows[0];return res.json({token:tok(u),user:{id:u.id,role:u.role,full_name:u.full_name},profile,sessionId:s.id})}u=(await q('SELECT * FROM users WHERE role=$1 AND email=$2',[role,(email||'').toLowerCase()])).rows[0];if(!u||!await bcrypt.compare(password||'',u.password_hash||''))return res.status(401).json({error:'Invalid login'});res.json({token:tok(u),user:{id:u.id,role:u.role,full_name:u.full_name,email:u.email}})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/logout',auth(['kid']),async(req,res)=>{const s=(await q('UPDATE learning_sessions SET logout_at=NOW(),active=FALSE,duration_seconds=GREATEST(0,EXTRACT(EPOCH FROM (NOW()-login_at))::int) WHERE id=$1 AND kid_id=$2 RETURNING duration_seconds',[req.body.sessionId,req.user.id])).rows[0];await act(req.user.id,'logout',null,'Student logged out',s||{});await notify(req.user.id,'kid_logout',req.user.name+' logged out after '+Math.round((s?.duration_seconds||0)/60)+' minutes.');res.json({ok:true})});
app.get('/api/kid/today',auth(['kid']),async(req,res)=>{const {p,today,mastery}=await kidContext(req.user.id);res.json({profile:p,assignments:today,mastery})});

app.post('/api/tutor',auth(['kid']),needAI,async(req,res)=>{try{const {p,today,mastery}=await kidContext(req.user.id);const subject=req.body.subject||today[0]?.subject||'';const message=(req.body.message||'').trim();if(!message)return res.status(400).json({error:'Ask a question first.'});const hist=(await q('SELECT role,content FROM ai_chat_messages WHERE kid_id=$1 AND ($2::text IS NULL OR subject=$2) ORDER BY created_at DESC LIMIT 8',[req.user.id,subject||null])).rows.reverse();const instructions=`You are Nova, the real AI tutor inside LearnMate AI for a child in India.\nStudent: ${p.full_name}; Class ${p.standard}; Board ${p.board}; preferred language ${p.language}; subjects ${JSON.stringify(p.subjects)}; interests ${JSON.stringify(p.interests)}.\nTeacher topics today: ${JSON.stringify(today)}. Mastery data: ${JSON.stringify(mastery)}.\nRules: teach, do not merely give final answers. Be age-appropriate, accurate, encouraging, concise, and safe. Match the student's preferred language. If the student uses Gujarati/Hinglish, reply naturally in the same mix. Use their interests for examples when useful. For maths/science, show reasoning step-by-step, then ask one short check-for-understanding question. Do not claim a topic is in their syllabus unless context says so.`;const input=`Recent conversation: ${JSON.stringify(hist)}\nStudent asks: ${message}`;await q("INSERT INTO ai_chat_messages(kid_id,subject,role,content) VALUES($1,$2,'user',$3)",[req.user.id,subject||null,message]);const answer=await aiText(instructions,input,1000);await q("INSERT INTO ai_chat_messages(kid_id,subject,role,content) VALUES($1,$2,'assistant',$3)",[req.user.id,subject||null,answer]);await act(req.user.id,'ai_tutor',subject,message.slice(0,120),{model:MODEL});res.json({answer,model:MODEL,realAI:true})}catch(e){res.status(500).json({error:'AI Tutor error: '+e.message})}});

app.post('/api/kid/quiz/start',auth(['kid']),needAI,async(req,res)=>{try{const {p,today,mastery}=await kidContext(req.user.id);const subject=req.body.subject||today[0]?.subject||p.subjects?.[0]||'General';const assignment=today.find(x=>x.subject===subject);const topic=req.body.topic||assignment?.topic||'Current class-level practice';const count=Math.min(10,Math.max(5,+req.body.count||5));const m=mastery.filter(x=>x.subject===subject);const instructions=`Generate an adaptive school quiz as strict JSON only. Student: Class ${p.standard}, ${p.board}, language ${p.language}. Subject: ${subject}. Topic: ${topic}. Teacher instruction: ${assignment?.instructions||''}. Mastery: ${JSON.stringify(m)}. Questions must be age-appropriate, unambiguous, curriculum-safe, and not trick questions. Vary difficulty based on mastery. Return exactly this JSON shape: {"questions":[{"question":"...","options":["A","B","C","D"],"correct_index":0,"explanation":"...","difficulty":"easy|medium|hard","concept":"..."}]}. Exactly ${count} questions, exactly 4 options each, correct_index integer 0-3.`;const data=await aiJSON(instructions,'Create the quiz now.',2400);if(!Array.isArray(data.questions)||data.questions.length<3)throw Error('AI returned an invalid quiz');const qs=data.questions.slice(0,count).map((x,i)=>({id:i+1,question:String(x.question),options:x.options.slice(0,4).map(String),correct_index:+x.correct_index,explanation:String(x.explanation||''),difficulty:String(x.difficulty||'medium'),concept:String(x.concept||topic)}));const sid=uuidv4();await q('INSERT INTO ai_quiz_sessions(id,kid_id,subject,topic,questions) VALUES($1,$2,$3,$4,$5::jsonb)',[sid,req.user.id,subject,topic,JSON.stringify(qs)]);await act(req.user.id,'ai_quiz_start',subject,topic,{count:qs.length,model:MODEL});res.json({quizSessionId:sid,subject,topic,source:'real-ai',questions:qs.map(({correct_index,explanation,...x})=>x)})}catch(e){res.status(500).json({error:'AI Quiz generation error: '+e.message})}});

app.post('/api/kid/quiz/submit',auth(['kid']),async(req,res)=>{try{const {quizSessionId,answers=[]}=req.body;const sess=(await q('SELECT * FROM ai_quiz_sessions WHERE id=$1 AND kid_id=$2',[quizSessionId,req.user.id])).rows[0];if(!sess)return res.status(404).json({error:'Quiz session not found'});if(sess.submitted_at)return res.status(409).json({error:'Quiz already submitted'});const qs=sess.questions;let correct=0;const detail=qs.map((z,i)=>{const a=answers.find(x=>+x.questionId===+z.id);const selected=a?+a.selectedIndex:-1;const ok=selected===+z.correct_index;if(ok)correct++;return {questionId:z.id,question:z.question,selectedIndex:selected,correctIndex:z.correct_index,correct:ok,explanation:z.explanation,difficulty:z.difficulty,concept:z.concept}});const total=detail.length,percent=total?Math.round(correct*10000/total)/100:0;const {p}=await kidContext(req.user.id);const r=(await q('INSERT INTO quiz_attempts(kid_id,subject,topic,board,standard,score,total,percent,detail,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10) RETURNING *',[req.user.id,sess.subject,sess.topic,p.board,p.standard,correct,total,percent,JSON.stringify(detail),'real-ai'])).rows[0];await q('UPDATE ai_quiz_sessions SET submitted_at=NOW() WHERE id=$1',[quizSessionId]);const old=(await q('SELECT score,attempts,correct_answers FROM mastery WHERE kid_id=$1 AND subject=$2 AND topic=$3',[req.user.id,sess.subject,sess.topic])).rows[0];const prev=old?+old.score:50;const blended=Math.max(0,Math.min(100,Math.round((prev*0.65+percent*0.35)*100)/100));const days=blended<40?1:blended<65?2:blended<80?4:7;await q(`INSERT INTO mastery(kid_id,subject,topic,score,attempts,correct_answers,last_practiced_at,next_revision_at) VALUES($1,$2,$3,$4,1,$5,NOW(),NOW()+($6||' days')::interval) ON CONFLICT(kid_id,subject,topic) DO UPDATE SET score=$4,attempts=mastery.attempts+1,correct_answers=mastery.correct_answers+$5,last_practiced_at=NOW(),next_revision_at=NOW()+($6||' days')::interval`,[req.user.id,sess.subject,sess.topic,blended,correct,String(days)]);await act(req.user.id,'quiz_complete',sess.subject,sess.topic,{score:correct,total,percent,mastery:blended});await notify(req.user.id,'quiz_complete',req.user.name+' completed '+sess.subject+' AI quiz: '+correct+'/'+total+' ('+percent+'%).');res.json({attempt:r,detail,mastery:{score:blended,nextRevisionDays:days}})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/parent/kids',auth(['parent']),async(req,res)=>res.json((await q('SELECT u.id,u.full_name,u.student_code,kp.* FROM users u JOIN kid_profiles kp ON kp.user_id=u.id WHERE kp.parent_id=$1',[req.user.id])).rows));
app.get('/api/teacher/students',auth(['teacher']),async(req,res)=>res.json((await q('SELECT u.id,u.full_name,u.student_code,kp.board,kp.standard,kp.language,kp.subjects FROM users u JOIN kid_profiles kp ON kp.user_id=u.id WHERE kp.teacher_id=$1',[req.user.id])).rows));
app.get('/api/notifications',auth(['parent','teacher']),async(req,res)=>res.json((await q('SELECT n.*,u.full_name kid_name FROM notifications n LEFT JOIN users u ON u.id=n.kid_id WHERE n.user_id=$1 ORDER BY n.created_at DESC LIMIT 100',[req.user.id])).rows));
async function accessOK(user,kid){return user.role==='parent'?(await q('SELECT 1 FROM kid_profiles WHERE user_id=$1 AND parent_id=$2',[kid,user.id])).rowCount:(await q('SELECT 1 FROM kid_profiles WHERE user_id=$1 AND teacher_id=$2',[kid,user.id])).rowCount}
app.get('/api/report/:kid',auth(['parent','teacher']),async(req,res)=>{const kid=+req.params.kid;if(!await accessOK(req.user,kid))return res.status(403).json({error:'No access'});const profile=(await q('SELECT u.full_name,u.student_code,kp.* FROM users u JOIN kid_profiles kp ON kp.user_id=u.id WHERE u.id=$1',[kid])).rows[0];const activities=(await q('SELECT * FROM activities WHERE kid_id=$1 ORDER BY created_at DESC LIMIT 100',[kid])).rows;const quizzes=(await q('SELECT * FROM quiz_attempts WHERE kid_id=$1 ORDER BY created_at DESC LIMIT 100',[kid])).rows;const summary=(await q('SELECT subject,ROUND(AVG(percent),1) avg_percent,COUNT(*) attempts FROM quiz_attempts WHERE kid_id=$1 GROUP BY subject ORDER BY avg_percent ASC',[kid])).rows;const mastery=(await q('SELECT * FROM mastery WHERE kid_id=$1 ORDER BY score ASC',[kid])).rows;const seconds=+(await q('SELECT COALESCE(SUM(duration_seconds),0) s FROM learning_sessions WHERE kid_id=$1',[kid])).rows[0].s;const suggestions=summary.map(x=>({subject:x.subject,level:+x.avg_percent<60?'Weak':+x.avg_percent<75?'Learning':'Good',text:+x.avg_percent<60?x.subject+' needs focused daily practice and AI Tutor revision.':+x.avg_percent<75?x.subject+' needs short quizzes and spaced revision.':x.subject+' is progressing well.'}));res.json({profile,activities,quizzes,subjectSummary:summary,mastery,studySeconds:seconds,suggestions})});
app.post('/api/report/:kid/ai-analysis',auth(['parent','teacher']),needAI,async(req,res)=>{try{const kid=+req.params.kid;if(!await accessOK(req.user,kid))return res.status(403).json({error:'No access'});const {p,today,mastery}=await kidContext(kid);const quizzes=(await q('SELECT subject,topic,score,total,percent,created_at FROM quiz_attempts WHERE kid_id=$1 ORDER BY created_at DESC LIMIT 25',[kid])).rows;const activities=(await q('SELECT activity_type,subject,title,created_at FROM activities WHERE kid_id=$1 ORDER BY created_at DESC LIMIT 40',[kid])).rows;const instructions=`You are LearnMate AI Learning Analyst. Analyze a child's learning data for a parent or teacher. Be practical, non-medical, non-diagnostic, and evidence-based. Never infer intelligence or sensitive traits. Give a concise report in ${p.language||'English'} or easy English if unclear. Structure with: Summary, Strengths, Needs Focus, 7-Day Action Plan, Teacher/Parent Note.`;const analysis=await aiText(instructions,JSON.stringify({profile:{class:p.standard,board:p.board,subjects:p.subjects},today,mastery,quizzes,activities}),1200);res.json({analysis,model:MODEL,realAI:true})}catch(e){res.status(500).json({error:'AI analysis error: '+e.message})}});
app.post('/api/teacher/assignment',auth(['teacher']),async(req,res)=>{const {board,standard,subject,topic,instructions}=req.body;if(!board||!standard||!subject||!topic)return res.status(400).json({error:'Board, standard, subject and topic are required'});const r=(await q('INSERT INTO teacher_assignments(teacher_id,board,standard,subject,topic,instructions) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.user.id,board,standard,subject,topic,instructions||''])).rows[0];res.json(r)});
app.get('/api/push/public-key',(req,res)=>res.json({publicKey:process.env.VAPID_PUBLIC_KEY||'',ready:pushReady}));
app.post('/api/push/subscribe',auth(['parent','teacher']),async(req,res)=>{if(!pushReady)return res.status(503).json({error:'Push is not configured'});const s=req.body.subscription;if(!s?.endpoint)return res.status(400).json({error:'Invalid subscription'});await q('INSERT INTO push_subscriptions(user_id,endpoint,subscription) VALUES($1,$2,$3::jsonb) ON CONFLICT(endpoint) DO UPDATE SET user_id=$1,subscription=$3::jsonb',[req.user.id,s.endpoint,JSON.stringify(s)]);res.json({ok:true})});
app.get('/health',(req,res)=>res.json({ok:true,realAI:!!ai,model:ai?MODEL:null,push:pushReady,database:true}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error'})});
http.listen(process.env.PORT||3000,()=>console.log(`LearnMate REAL AI started on ${process.env.PORT||3000}; AI=${!!ai}; model=${MODEL}`));
